name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  tag:
    name: Add/update 'latest' tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Install Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish on GPR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Install Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@snazzah'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Package
        run: pnpm run build

      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-jsr:
    name: Publish on JSR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: npx jsr publish
